# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simulation_ur3/PosTracker.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PosTracker(genpy.Message):
  _md5sum = "89129e0c6ca6b02f521b2e681ee9b035"
  _type = "simulation_ur3/PosTracker"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# message type to describe the tracking information of the end effector
# to be published as a topic

float64 c_X  # current X
float64 c_Y  # current Y
float64 c_Z  # current Z
float64 g_X  # goal X
float64 g_Y  # goal Y
float64 g_Z  # goal Z
"""
  __slots__ = ['c_X','c_Y','c_Z','g_X','g_Y','g_Z']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       c_X,c_Y,c_Z,g_X,g_Y,g_Z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PosTracker, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.c_X is None:
        self.c_X = 0.
      if self.c_Y is None:
        self.c_Y = 0.
      if self.c_Z is None:
        self.c_Z = 0.
      if self.g_X is None:
        self.g_X = 0.
      if self.g_Y is None:
        self.g_Y = 0.
      if self.g_Z is None:
        self.g_Z = 0.
    else:
      self.c_X = 0.
      self.c_Y = 0.
      self.c_Z = 0.
      self.g_X = 0.
      self.g_Y = 0.
      self.g_Z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.c_X, _x.c_Y, _x.c_Z, _x.g_X, _x.g_Y, _x.g_Z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.c_X, _x.c_Y, _x.c_Z, _x.g_X, _x.g_Y, _x.g_Z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.c_X, _x.c_Y, _x.c_Z, _x.g_X, _x.g_Y, _x.g_Z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.c_X, _x.c_Y, _x.c_Z, _x.g_X, _x.g_Y, _x.g_Z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
