controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  # - name: joint_group_vel_controller
  #     type: velocity_controllers/JointGroupVelocityController
  #   joints:
  #      - shoulder_pan_joint
  #      - shoulder_lift_joint
  #      - elbow_joint
  #      - wrist_1_joint
  #      - wrist_2_joint
  #      - wrist_3_joint
#
# controller_list:
#   - name: ""
#     type: velocity_controllers/JointGroupVelocityController
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
